server:
  port: 9090
spring:
  application:
    name: product
  datasource:
    url: jdbc:h2:mem:testdb  # In-memory database
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update  # Automatically create or update the database schema. Use 'create' for schema creation on app startup, or 'none' to disable auto-creation.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # Set H2 dialect for Hibernate
    show-sql: true  # Enable this to show the SQL queries in the logs
  h2:
    console:
      enabled: true  # Enable H2 console for development purposes
      path: /h2
